export const SEGMENT_FILE_NO_SEPERATOR = 'PART';
export const SEGMENT_TEMP_FOLDER = '_appdata/_temp/';
export const SEGMENT_TARGET_DURATION = 3;
export const FAST_START_SEGMENTS = 50;
export const FAST_START_TIME = SEGMENT_TARGET_DURATION * FAST_START_SEGMENTS;
